name: Image Build and Upload to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG="${DOCKER_REPO_NAME}:latest"

          docker build -t ${IMAGE_TAG} .

          docker push ${IMAGE_TAG}
        env:
          DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
